# Generated by Django 3.2.15 on 2022-10-17 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='Player',
            name='address',
        ),
        migrations.RemoveField(
            model_name='Player',
            name='subject_name',
        ),
    ]
